"use strict";
exports.__esModule = true;
require("@babel/polyfill");
var provide_1 = require("./global/provide");
exports.provide = provide_1["default"];
var Provider_1 = require("./global/Provider");
exports.getProvider = Provider_1.getProvider;
var index_1 = require("./region/index");
exports.Region = index_1["default"];
provide_1["default"]();
