"use strict";
exports.__esModule = true;
require("@babel/polyfill");
var provide_1 = require("./global/provide");
exports.provide = provide_1["default"];
var Provider_1 = require("./global/Provider");
exports.getProvider = Provider_1.getProvider;
var region_1 = require("./region");
exports.Region = region_1["default"];
provide_1["default"]();
